//STANDARD SOCKET UPDATES
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const UPDATE_SENTIMENT = 'UPDATE_SENTIMENT';
export const UPDATE_TRAFFIC_GEN = 'UPDATE_TRAFFIC_GEN';

//API TRACKING
export const SEND_REQUEST = 'SEND_REQUEST';
export const CLEAR_STORE = 'CLEAR_STORE';

//PINNED TWEETS
export const CREATE_PINNED_TWEET = 'CREATE_PINNED_TWEET';
export const EDIT_PINNED_TWEET = 'CREATE_PINNED_TWEET';
export const DELETE_PINNED_TWEET = 'DELETE_PINNED_TWEET';

//PRESETS
export const CREATE_PRESET = 'CREATE_PRESET';
export const EDIT_PRESET = 'EDIT_PRESET';
export const DELETE_PRESET = 'DELETE_PRESET';
export const GET_PRESETS = 'GET_PRESETS';

//SOCIAL FILTERS
export const CREATE_SOCIAL_FILTER = 'CREATE_SOCIAL_FILTER';
export const EDIT_SOCIAL_FILTER = 'EDIT_SOCIAL_FILTER';
export const DELETE_SOCIAL_FILTER = 'DELETE_SOCIAL_FILTER';
export const GET_SOCIAL_FILTERS = 'GET_SOCIAL_FILTERS';
