//STANDARD SOCKET UPDATES
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const UPDATE_SENTIMENT = 'UPDATE_SENTIMENT';
export const UPDATE_TRAFFIC_GEN = 'UPDATE_TRAFFIC_GEN';

//API TRACKING
export const SEND_REQUEST = 'SEND_REQUEST';
export const CLEAR_STORE = 'CLEAR_STORE';

//PINNED TWEETS
export const CREATE_PINNED_TWEET = 'CREATE_PINNED_TWEET';
export const DELETE_PINNED_TWEET = 'DELETE_PINNED_TWEET';
export const CLEAR_PINNED_TWEETS = 'CLEAR_PINNED_TWEETS';

//PRESETS
export const CREATE_PRESET = 'CREATE_PRESET';
export const EDIT_PRESET = 'EDIT_PRESET';
export const DELETE_PRESET = 'DELETE_PRESET';
export const GET_PRESETS = 'GET_PRESETS';

//FILTERS
export const EDIT_FILTERS = 'EDIT_FILTERS';

//TIME
export const UPDATE_TIME = 'UPDATE_TIME';
